//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2", IsNullable=false)]
public partial class VATDeclarationResponse {
    
    private VATDeclarationResponseHeader headerField;
    
    private VATDeclarationResponseBody bodyField;
    
    private string schemaVersionField;
    
    /// <remarks/>
    public VATDeclarationResponseHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    public VATDeclarationResponseBody Body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string SchemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class VATDeclarationResponseHeader {
    
    private VATPeriodType vATPeriodField;
    
    private string currencyCodeField;
    
    private ExtensionPartType extensionPartField;
    
    public VATDeclarationResponseHeader() {
        this.currencyCodeField = "GBP";
    }
    
    /// <remarks/>
    public VATPeriodType VATPeriod {
        get {
            return this.vATPeriodField;
        }
        set {
            this.vATPeriodField = value;
        }
    }
    
    /// <remarks/>
    public string CurrencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
    
    /// <remarks/>
    public ExtensionPartType ExtensionPart {
        get {
            return this.extensionPartField;
        }
        set {
            this.extensionPartField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class VATPeriodType {
    
    private string periodIdField;
    
    private System.DateTime periodStartDateField;
    
    private bool periodStartDateFieldSpecified;
    
    private System.DateTime periodEndDateField;
    
    private bool periodEndDateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYearMonth")]
    public string PeriodId {
        get {
            return this.periodIdField;
        }
        set {
            this.periodIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime PeriodStartDate {
        get {
            return this.periodStartDateField;
        }
        set {
            this.periodStartDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PeriodStartDateSpecified {
        get {
            return this.periodStartDateFieldSpecified;
        }
        set {
            this.periodStartDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime PeriodEndDate {
        get {
            return this.periodEndDateField;
        }
        set {
            this.periodEndDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PeriodEndDateSpecified {
        get {
            return this.periodEndDateFieldSpecified;
        }
        set {
            this.periodEndDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class PaymentRequestType {
    
    private DirectDebitInstructionStatusType directDebitInstructionStatusField;
    
    /// <remarks/>
    public DirectDebitInstructionStatusType DirectDebitInstructionStatus {
        get {
            return this.directDebitInstructionStatusField;
        }
        set {
            this.directDebitInstructionStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public enum DirectDebitInstructionStatusType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Not Eligible For Direct Debit")]
    NotEligibleForDirectDebit,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Direct Debit Not Set-up")]
    DirectDebitNotSetup,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Direct Debit Not Yet Effective")]
    DirectDebitNotYetEffective,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class DirectDebitPaymentStatusType {
    
    private System.DateTime collectionDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime CollectionDate {
        get {
            return this.collectionDateField;
        }
        set {
            this.collectionDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class RepaymentIndicatorType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class NilPaymentIndicatorType {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentNotificationType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class NotificationType {
    
    private string narrativeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Narrative {
        get {
            return this.narrativeField;
        }
        set {
            this.narrativeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class PaymentNotificationType : NotificationType {
    
    private decimal netVATField;
    
    private object itemField;
    
    private decimal aASBalancingPaymentField;
    
    private bool aASBalancingPaymentFieldSpecified;
    
    /// <remarks/>
    public decimal NetVAT {
        get {
            return this.netVATField;
        }
        set {
            this.netVATField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DirectDebitPaymentStatus", typeof(DirectDebitPaymentStatusType))]
    [System.Xml.Serialization.XmlElementAttribute("NilPaymentIndicator", typeof(NilPaymentIndicatorType))]
    [System.Xml.Serialization.XmlElementAttribute("PaymentRequest", typeof(PaymentRequestType))]
    [System.Xml.Serialization.XmlElementAttribute("RepaymentIndicator", typeof(RepaymentIndicatorType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    public decimal AASBalancingPayment {
        get {
            return this.aASBalancingPaymentField;
        }
        set {
            this.aASBalancingPaymentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AASBalancingPaymentSpecified {
        get {
            return this.aASBalancingPaymentFieldSpecified;
        }
        set {
            this.aASBalancingPaymentFieldSpecified = value;
        }
    }
}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
//public partial class ExtensionPartType {
    
//    private System.Xml.XmlElement[] anyField;
    
//    private System.Xml.XmlAttribute[] anyAttrField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAnyElementAttribute()]
//    public System.Xml.XmlElement[] Any {
//        get {
//            return this.anyField;
//        }
//        set {
//            this.anyField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
//    public System.Xml.XmlAttribute[] AnyAttr {
//        get {
//            return this.anyAttrField;
//        }
//        set {
//            this.anyAttrField = value;
//        }
//    }
//}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class VATDeclarationResponseBody {
    
    private System.DateTime paymentDueDateField;
    
    private string vATDeclarationReferenceField;
    
    private System.DateTime receiptTimestampField;
    
    private PaymentNotificationType paymentNotificationField;
    
    private NotificationType[] informationNotificationField;
    
    private ExtensionPartType[] extensionPartField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime PaymentDueDate {
        get {
            return this.paymentDueDateField;
        }
        set {
            this.paymentDueDateField = value;
        }
    }
    
    /// <remarks/>
    public string VATDeclarationReference {
        get {
            return this.vATDeclarationReferenceField;
        }
        set {
            this.vATDeclarationReferenceField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ReceiptTimestamp {
        get {
            return this.receiptTimestampField;
        }
        set {
            this.receiptTimestampField = value;
        }
    }
    
    /// <remarks/>
    public PaymentNotificationType PaymentNotification {
        get {
            return this.paymentNotificationField;
        }
        set {
            this.paymentNotificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InformationNotification")]
    public NotificationType[] InformationNotification {
        get {
            return this.informationNotificationField;
        }
        set {
            this.informationNotificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExtensionPart")]
    public ExtensionPartType[] ExtensionPart {
        get {
            return this.extensionPartField;
        }
        set {
            this.extensionPartField = value;
        }
    }
}
