//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2", IsNullable=false)]
public partial class IRenvelope {
    
    private IRheader iRheaderField;
    
    private VATDeclarationRequest vATDeclarationRequestField;
    //private string _irMark = null;
    /// <remarks/>
    public IRheader IRheader {
        get {
            return this.iRheaderField;
        }
        set {
            this.iRheaderField = value;
        }
    }
    
    /// <remarks/>
    public VATDeclarationRequest VATDeclarationRequest {
        get {
            return this.vATDeclarationRequestField;
        }
        set {
            this.vATDeclarationRequestField = value;
        }
    }
    //public string IRMark
    //{
    //    get { return this._irMark; }
    //    set { this._irMark = value; }
    //}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2", IsNullable=false)]
public partial class IRheader {
    
    private IRheaderKey[] keysField;
    
    private string periodIDField;
    
    private System.DateTime periodStartField;
    
    private bool periodStartFieldSpecified;
    
    private System.DateTime periodEndField;
    
    private bool periodEndFieldSpecified;
    
    private IRheaderPrincipal principalField;
    
    private IRheaderAgent agentField;
    
    private IRheaderDefaultCurrency defaultCurrencyField;
    
    private bool defaultCurrencyFieldSpecified;
    
    private IRheaderManifest manifestField;
    
    private IRheaderIRmark iRmarkField;
    
    private IRheaderSender senderField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Key", IsNullable=false)]
    public IRheaderKey[] Keys {
        get {
            return this.keysField;
        }
        set {
            this.keysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYearMonth")]
    public string PeriodID {
        get {
            return this.periodIDField;
        }
        set {
            this.periodIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime PeriodStart {
        get {
            return this.periodStartField;
        }
        set {
            this.periodStartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PeriodStartSpecified {
        get {
            return this.periodStartFieldSpecified;
        }
        set {
            this.periodStartFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime PeriodEnd {
        get {
            return this.periodEndField;
        }
        set {
            this.periodEndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PeriodEndSpecified {
        get {
            return this.periodEndFieldSpecified;
        }
        set {
            this.periodEndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public IRheaderPrincipal Principal {
        get {
            return this.principalField;
        }
        set {
            this.principalField = value;
        }
    }
    
    /// <remarks/>
    public IRheaderAgent Agent {
        get {
            return this.agentField;
        }
        set {
            this.agentField = value;
        }
    }
    
    /// <remarks/>
    public IRheaderDefaultCurrency DefaultCurrency {
        get {
            return this.defaultCurrencyField;
        }
        set {
            this.defaultCurrencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DefaultCurrencySpecified {
        get {
            return this.defaultCurrencyFieldSpecified;
        }
        set {
            this.defaultCurrencyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public IRheaderManifest Manifest {
        get {
            return this.manifestField;
        }
        set {
            this.manifestField = value;
        }
    }
    
    /// <remarks/>
    public IRheaderIRmark IRmark {
        get {
            return this.iRmarkField;
        }
        set {
            this.iRmarkField = value;
        }
    }
    
    /// <remarks/>
    public IRheaderSender Sender {
        get {
            return this.senderField;
        }
        set {
            this.senderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class IRheaderKey {
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class ExtensionPartType {
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class VATDeclarationRequest_TelephoneStructure {
    
    private string numberField;
    
    private string extensionField;
    
    private VATDeclarationRequest_WorkHomeType typeField;
    
    private bool typeFieldSpecified;
    
    private VATDeclarationRequest_YesNoType mobileField;
    
    private bool mobileFieldSpecified;
    
    private VATDeclarationRequest_YesNoType preferredField;
    
    private bool preferredFieldSpecified;
    
    /// <remarks/>
    public string Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    public string Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VATDeclarationRequest_WorkHomeType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TypeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VATDeclarationRequest_YesNoType Mobile {
        get {
            return this.mobileField;
        }
        set {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MobileSpecified {
        get {
            return this.mobileFieldSpecified;
        }
        set {
            this.mobileFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VATDeclarationRequest_YesNoType Preferred {
        get {
            return this.preferredField;
        }
        set {
            this.preferredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PreferredSpecified {
        get {
            return this.preferredFieldSpecified;
        }
        set {
            this.preferredFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public enum VATDeclarationRequest_WorkHomeType {
    
    /// <remarks/>
    home,
    
    /// <remarks/>
    work,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public enum VATDeclarationRequest_YesNoType {
    
    /// <remarks/>
    no,
    
    /// <remarks/>
    yes,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class VATDeclarationRequest_ContactDetailsStructure {
    
    private VATDeclarationRequest_ContactDetailsStructureName nameField;
    
    private VATDeclarationRequest_ContactDetailsStructureEmail[] emailField;
    
    private VATDeclarationRequest_TelephoneStructure[] telephoneField;
    
    private VATDeclarationRequest_TelephoneStructure[] faxField;
    
    /// <remarks/>
    public VATDeclarationRequest_ContactDetailsStructureName Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Email")]
    public VATDeclarationRequest_ContactDetailsStructureEmail[] Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Telephone")]
    public VATDeclarationRequest_TelephoneStructure[] Telephone {
        get {
            return this.telephoneField;
        }
        set {
            this.telephoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Fax")]
    public VATDeclarationRequest_TelephoneStructure[] Fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class VATDeclarationRequest_ContactDetailsStructureName {
    
    private string ttlField;
    
    private string[] foreField;
    
    private string surField;
    
    /// <remarks/>
    public string Ttl {
        get {
            return this.ttlField;
        }
        set {
            this.ttlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Fore")]
    public string[] Fore {
        get {
            return this.foreField;
        }
        set {
            this.foreField = value;
        }
    }
    
    /// <remarks/>
    public string Sur {
        get {
            return this.surField;
        }
        set {
            this.surField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class VATDeclarationRequest_ContactDetailsStructureEmail {
    
    private VATDeclarationRequest_WorkHomeType typeField;
    
    private bool typeFieldSpecified;
    
    private VATDeclarationRequest_YesNoType preferredField;
    
    private bool preferredFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VATDeclarationRequest_WorkHomeType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TypeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VATDeclarationRequest_YesNoType Preferred {
        get {
            return this.preferredField;
        }
        set {
            this.preferredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PreferredSpecified {
        get {
            return this.preferredFieldSpecified;
        }
        set {
            this.preferredFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class IRheaderPrincipal {
    
    private VATDeclarationRequest_ContactDetailsStructure contactField;
    
    /// <remarks/>
    public VATDeclarationRequest_ContactDetailsStructure Contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class IRheaderAgent {
    
    private string agentIDField;
    
    private string companyField;
    
    private IRheaderAgentAddress addressField;
    
    private VATDeclarationRequest_ContactDetailsStructure contactField;
    
    /// <remarks/>
    public string AgentID {
        get {
            return this.agentIDField;
        }
        set {
            this.agentIDField = value;
        }
    }
    
    /// <remarks/>
    public string Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    public IRheaderAgentAddress Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public VATDeclarationRequest_ContactDetailsStructure Contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class IRheaderAgentAddress {
    
    private string[] lineField;
    
    private string postCodeField;
    
    private string countryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Line")]
    public string[] Line {
        get {
            return this.lineField;
        }
        set {
            this.lineField = value;
        }
    }
    
    /// <remarks/>
    public string PostCode {
        get {
            return this.postCodeField;
        }
        set {
            this.postCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public enum IRheaderDefaultCurrency {
    
    /// <remarks/>
    GBP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class IRheaderManifest {
    
    private IRheaderManifestReference[] containsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Reference", IsNullable=false)]
    public IRheaderManifestReference[] Contains {
        get {
            return this.containsField;
        }
        set {
            this.containsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class IRheaderManifestReference {
    
    private string namespaceField;
    
    private string schemaVersionField;
    
    private string topElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string Namespace {
        get {
            return this.namespaceField;
        }
        set {
            this.namespaceField = value;
        }
    }
    
    /// <remarks/>
    public string SchemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string TopElementName {
        get {
            return this.topElementNameField;
        }
        set {
            this.topElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public partial class IRheaderIRmark {
    
    private IRheaderIRmarkType typeField;
    
    private string valueField;
    //private string _irMark = null;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public IRheaderIRmarkType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    //public string IRMark
    //{
    //    get { return this._irMark; }
    //    set { this._irMark = value; }
    //}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public enum IRheaderIRmarkType {
    
    /// <remarks/>
    generic,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public enum IRheaderSender {
    
    /// <remarks/>
    Individual,
    
    /// <remarks/>
    Company,
    
    /// <remarks/>
    Agent,
    
    /// <remarks/>
    Bureau,
    
    /// <remarks/>
    Partnership,
    
    /// <remarks/>
    Trust,
    
    /// <remarks/>
    Employer,
    
    /// <remarks/>
    Government,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Acting in Capacity")]
    ActinginCapacity,
    
    /// <remarks/>
    Other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2", IsNullable=false)]
public partial class VATDeclarationRequest {
    
    private string vATDueOnOutputsField;
    
    private string vATDueOnECAcquisitionsField;
    
    private string totalVATField;
    
    private string vATReclaimedOnInputsField;
    
    private string netVATField;
    
    private string netSalesAndOutputsField;
    
    private string netPurchasesAndInputsField;
    
    private string netECSuppliesField;
    
    private string netECAcquisitionsField;
    
    private decimal aASBalancingPaymentField;
    
    private bool aASBalancingPaymentFieldSpecified;
    
    private ExtensionPartType[] extensionPartField;
    
    private VATDeclarationRequestFinalReturn finalReturnField;
    
    private bool finalReturnFieldSpecified;

    ///<starthandwrittencode/>
    ///
    /// <remarks/>
    /// 
    //[ForeignKey("PeriodData")]
    //public int PeriodVATId { get; set; }
    //public virtual ASA.Core.PeriodData PeriordData { get; set; }
    public string VATDueOnOutputs {
        get {
            return this.vATDueOnOutputsField;
        }
        set {
            this.vATDueOnOutputsField = value;
        }
    }
    
    /// <remarks/>
    public string VATDueOnECAcquisitions {
        get {
            return this.vATDueOnECAcquisitionsField;
        }
        set {
            this.vATDueOnECAcquisitionsField = value;
        }
    }
    
    /// <remarks/>
    public string TotalVAT {
        get {
            return this.totalVATField;
        }
        set {
            this.totalVATField = value;
        }
    }
    
    /// <remarks/>
    public string VATReclaimedOnInputs {
        get {
            return this.vATReclaimedOnInputsField;
        }
        set {
            this.vATReclaimedOnInputsField = value;
        }
    }
    
    /// <remarks/>
    public string NetVAT {
        get {
            return this.netVATField;
        }
        set {
            this.netVATField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NetSalesAndOutputs {
        get {
            return this.netSalesAndOutputsField;
        }
        set {
            this.netSalesAndOutputsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NetPurchasesAndInputs {
        get {
            return this.netPurchasesAndInputsField;
        }
        set {
            this.netPurchasesAndInputsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NetECSupplies {
        get {
            return this.netECSuppliesField;
        }
        set {
            this.netECSuppliesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NetECAcquisitions {
        get {
            return this.netECAcquisitionsField;
        }
        set {
            this.netECAcquisitionsField = value;
        }
    }
    
    /// <remarks/>
    public decimal AASBalancingPayment {
        get {
            return this.aASBalancingPaymentField;
        }
        set {
            this.aASBalancingPaymentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AASBalancingPaymentSpecified {
        get {
            return this.aASBalancingPaymentFieldSpecified;
        }
        set {
            this.aASBalancingPaymentFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExtensionPart")]
    public ExtensionPartType[] ExtensionPart {
        get {
            return this.extensionPartField;
        }
        set {
            this.extensionPartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VATDeclarationRequestFinalReturn finalReturn {
        get {
            return this.finalReturnField;
        }
        set {
            this.finalReturnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool finalReturnSpecified {
        get {
            return this.finalReturnFieldSpecified;
        }
        set {
            this.finalReturnFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/vat/vatdeclaration/2")]
public enum VATDeclarationRequestFinalReturn {
    
    /// <remarks/>
    yes,
}
